/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction */

#ifndef _Included_com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction
#define _Included_com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction_div
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction
 * Method:    addWithOverflowCheck
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_systemprogramm_controllermodels_lowlevelfunction_LowLevelFunction_addWithOverflowCheck
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
